"""nuevos modulos comunidad

Revision ID: 9aec2efa12cd
Revises:
Create Date: 2026-08-12 14:10:21.158923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aec2efa12cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administradores_id'), 'administradores', ['id'], unique=False)
    op.create_table('avisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('activo', sa.String(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avisos_id'), 'avisos', ['id'], unique=False)
    op.create_table('configuraciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_index(op.f('ix_configuraciones_id'), 'configuraciones', ['id'], unique=False)
    op.create_table('estados_cuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad', sa.String(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('saldo_inicial', sa.Float(), nullable=False),
    sa.Column('ingresos', sa.Float(), nullable=False),
    sa.Column('gastos', sa.Float(), nullable=False),
    sa.Column('saldo_final', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_cuenta_id'), 'estados_cuenta', ['id'], unique=False)
    op.create_table('telefonos_interes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telefonos_interes_id'), 'telefonos_interes', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('vecinos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('piso', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('portal_activo', sa.String(), nullable=False),
    sa.Column('codigo_invitacion', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('es_presidente', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_invitacion')
    )
    op.create_index(op.f('ix_vecinos_id'), 'vecinos', ['id'], unique=False)
    op.create_table('carnets_piscina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vecino_id', sa.Integer(), nullable=False),
    sa.Column('numero_carnet', sa.String(), nullable=False),
    sa.Column('fecha_expedicion', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vecino_id'], ['vecinos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_carnet'),
    sa.UniqueConstraint('vecino_id')
    )
    op.create_index(op.f('ix_carnets_piscina_id'), 'carnets_piscina', ['id'], unique=False)
    op.create_table('delegaciones_voto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vecino_delegante_id', sa.Integer(), nullable=False),
    sa.Column('vecino_delegado_id', sa.Integer(), nullable=False),
    sa.Column('dni_delegante', sa.String(), nullable=True),
    sa.Column('asunto', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('fecha_validez', sa.DateTime(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vecino_delegado_id'], ['vecinos.id'], ),
    sa.ForeignKeyConstraint(['vecino_delegante_id'], ['vecinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegaciones_voto_id'), 'delegaciones_voto', ['id'], unique=False)
    op.create_table('invitaciones_piscina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vecino_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('total_asignadas', sa.Integer(), nullable=False),
    sa.Column('usadas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vecino_id'], ['vecinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitaciones_piscina_id'), 'invitaciones_piscina', ['id'], unique=False)
    op.create_table('llaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('prestada_a', sa.String(), nullable=True),
    sa.Column('vecino_id', sa.Integer(), nullable=True),
    sa.Column('desde', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vecino_id'], ['vecinos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_llaves_id'), 'llaves', ['id'], unique=False)
    op.create_table('paquetes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remitente', sa.String(), nullable=True),
    sa.Column('vecino_id', sa.Integer(), nullable=False),
    sa.Column('tracking', sa.String(), nullable=True),
    sa.Column('tamanio', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('notificado', sa.String(), nullable=False),
    sa.Column('recibido_en', sa.DateTime(), nullable=False),
    sa.Column('entregado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vecino_id'], ['vecinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paquetes_id'), 'paquetes', ['id'], unique=False)
    op.create_table('quejas_mejoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('asunto', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('prioridad', sa.String(), nullable=False),
    sa.Column('vecino_id', sa.Integer(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('foto_path', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['vecino_id'], ['vecinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quejas_mejoras_id'), 'quejas_mejoras', ['id'], unique=False)
    op.create_table('registros_piscina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vecino_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('nombre_invitado', sa.String(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['vecino_id'], ['vecinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_piscina_id'), 'registros_piscina', ['id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asunto', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('prioridad', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('piso', sa.String(), nullable=True),
    sa.Column('vecino_id', sa.Integer(), nullable=True),
    sa.Column('asignado_a', sa.String(), nullable=True),
    sa.Column('foto_path', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['vecino_id'], ['vecinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('autor', sa.String(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarios_id'), 'comentarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comentarios_id'), table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_registros_piscina_id'), table_name='registros_piscina')
    op.drop_table('registros_piscina')
    op.drop_index(op.f('ix_quejas_mejoras_id'), table_name='quejas_mejoras')
    op.drop_table('quejas_mejoras')
    op.drop_index(op.f('ix_paquetes_id'), table_name='paquetes')
    op.drop_table('paquetes')
    op.drop_index(op.f('ix_llaves_id'), table_name='llaves')
    op.drop_table('llaves')
    op.drop_index(op.f('ix_invitaciones_piscina_id'), table_name='invitaciones_piscina')
    op.drop_table('invitaciones_piscina')
    op.drop_index(op.f('ix_delegaciones_voto_id'), table_name='delegaciones_voto')
    op.drop_table('delegaciones_voto')
    op.drop_index(op.f('ix_carnets_piscina_id'), table_name='carnets_piscina')
    op.drop_table('carnets_piscina')
    op.drop_index(op.f('ix_vecinos_id'), table_name='vecinos')
    op.drop_table('vecinos')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_telefonos_interes_id'), table_name='telefonos_interes')
    op.drop_table('telefonos_interes')
    op.drop_index(op.f('ix_estados_cuenta_id'), table_name='estados_cuenta')
    op.drop_table('estados_cuenta')
    op.drop_index(op.f('ix_configuraciones_id'), table_name='configuraciones')
    op.drop_table('configuraciones')
    op.drop_index(op.f('ix_avisos_id'), table_name='avisos')
    op.drop_table('avisos')
    op.drop_index(op.f('ix_administradores_id'), table_name='administradores')
    op.drop_table('administradores')
    # ### end Alembic commands ###
